import Head from "next/head";

//components
import HomeTopSection from "@/components/HomeTopSection/HomeTopSection";
import RelatedProductsFilter from "@/components/RelatedProductsFilter/RelatedProductsFilter";
import RelatedProducts from "@/components/RelatedProducts/RelatedProducts";
import Partners from "@/components/Partners/Partners";
import RelatedProductsSeeAll from "@/components/RelatedProductsSeeAll/RelatedProductsSeeAll";
import BrandNavigation from "@/components/BrandNavigation/BrandNavigation";

import Layout from "@/components/Layout/Layout";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teste Vaga Front-End Júnior</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Layout>
        <HomeTopSection />

        <RelatedProductsFilter />

        <RelatedProducts />

        <Partners />

        <RelatedProductsSeeAll />

        <Partners />

        <BrandNavigation />

        <RelatedProductsSeeAll />
      </Layout>
    </>
  );
}
